### ISSUE TITLE
Remove SAS mysql dependency + change output of KnoxAutoPolicy

### ISSUE THREAD

**Issue by asifalix** [accuknox/discovery-engine#367]
Remove mysql on the SAAS environment and make it run locally without dependencies
Any external party should follow do not call me, I will call you principle
Decoupled completely to run independently.
Discovers, aggregates everything locally [can continue to use a local mysql if needed]
Uses a config file including secrets to push to common storage (git)
Output on STDIO as well as Files and or Github (as configured)

**Comment by nyrahul** [comment]
Policy-Discovery now works in standard linux process mode without SaaS or k8s dependency.
Output can be to DB or file as configured.
