### ISSUE TITLE
Provide a CLI to view auto generated policies directly on CLI

### ISSUE THREAD

**Issue by asifalix** [accuknox/discovery-engine#368]
Provide a CLI that provides an aggregated view of the auto generated policies
Aggregations happen and state is remembered (when the system starts up again). 
The auto policy system resumes where it left off on policies..
Output should also be available as YAML
Output should also include config mapping of policies <> clusters and namespaces

**Comment by nyrahul** [comment]
We have a cli which handles thsi now. Hence closing this issue.
