### ISSUE TITLE
purge policy entries from DB

### ISSUE THREAD

**Issue by nyrahul** [accuknox/discovery-engine#395]
Currently, the policy entries never get purged. Policy entries might be added as a result of user-experimentation in which user might want to delete the corresponding entries.

Following are the user-scenarios:
#### As a user, I want to delete a specific entry from the policy/DB such that it does not reflect in the auto-discovered policies in the future. I want to delete it since I executed the command for experimentation purpose and is not required.

A1. Delete all entries related to a given process in a given container of a deployment
```
./db-clear.sh --clustername xyz --containername abc --namespace myns --fromSource /usr/bin/bash
```
A2. Delete all entries related to a given process across all containers
```
./db-clear.sh --fromSource /usr/bin/bash
```
A3. Delete all entries created in last 1 hour
```
./db-clear.sh --since 1h
```

#### As a user, I want to delete all policies discovered for a given workload
A4. Delete all entries for a given workload
```
./db-clear.sh --clustername xyz --containername abc --namespace myns
```

3. As a user, I want to start building discovered policies afresh
A5. Delete all entries
```
./db-clear.sh
```

Tasklist:
- [x] A1
- [x] A2
- [x] A3
- [x] A4
- [x] A5

**Comment by nyrahul** [comment]
@seswarrajan , can you check the requirements mentioned herewith for the PR #398 you raised?

**Comment by seswarrajan** [comment]
@nyrahul  All tasks in purging the DB is completed. Kindly try and provide your comments.

**Comment by seswarrajan** [comment]
@nyrahul  The purging DB tasks are complete. This issue can be closed.
