### ISSUE TITLE
auto discovery of system policies for VMs/Bare-metal

### ISSUE THREAD

**Issue by nyrahul** [accuknox/discovery-engine#409]
Kubearmor supports visibility/enforcement for the VMs/Bare-metal. The auto-policy-discovery should be able to generate host based policies for such deployments.

**Comment by seswarrajan** [comment]
With latest changes discovery-engine is able to auto-generate policies for VM/Bare-metals in both systemd mode and kvmservice mode. 
All this generated policies can be extracted using karmor CLI.
