### ISSUE TITLE
Getting too many logs when discovery engine's observability in enabled

### ISSUE THREAD

**Issue by Ankurk99** [accuknox/discovery-engine#530]
**Describe the problem**
When observability is enabled, discovery engine is accessing the sqlite3 db very frequently. This in turn results in lots of unnecessary logs in kubearmor telemetry.

**Reasons for the problem**
- receiving knoxAutoPolicy's own logs
- performing "insert" operation multiple times on db 
- Inserting identical logs

**Comment by Ankurk99** [comment]
ref #531

**Comment by seswarrajan** [comment]
All the above points were handle in latest. The changes will soon be merged into stable.
