### ISSUE TITLE
KARMOR (kubearmor-client) summary output display update

### ISSUE THREAD

**Issue by seswarrajan** [accuknox/discovery-engine#567]
- [ ] modify karmor summary output to match all recent fields added. (we don't need this)
- [ ] Display summary output per deployment and not per pod. (we don't need this)
- [x] Add colors(RED,GREEN) for ALLOW/DENY states if possible.

**Comment by yasin-cs-ko-ak** [comment]
@seswarrajan This issue can be marked as done/closed.
cc: @nyrahul

**Comment by seswarrajan** [comment]
PR is merged and all tasks are completed.
