### ISSUE TITLE
Remove namespace dependency for KubeArmor

### ISSUE THREAD

**Issue by Ankurk99** [accuknox/discovery-engine#660]
**Description**
Currently Discovery Engine configuration checks for KubeArmor in the default kube-system namespace only. If KubeArmor is installed in any other namespace then it won't be able to communicate with that. 
It causes a problem that we can't really install KubeArmor in other namespace and use discovery-engine with it. 

**Solution**
The aim is to remove this the dependency on kube-system namespace and use another one (for eg. `kubearmor` namespace). Then we will be installing KubeArmor in `kubearmor` namespace by default.

**Comment by Prateeknandle** [comment]
@Ankurk99 do we want to replace the default namespace from `kube-system` to `kubearmor` or should we implement something that will check kubearmor not based on namespace?

**Comment by Ankurk99** [comment]
@Prateeknandle The plan we have is to be able to install KubeArmor in any namespace so we should go with that logic
