### ISSUE TITLE
[Bug] Discovered Network Policies sometimes are not getting correctly/accuratly generated

### ISSUE THREAD

**Issue by Prateeknandle** [accuknox/discovery-engine#666]
For ex - [https://github.com/accuknox/discovery-engine/actions/runs/4118258190/jobs/7155494607#step:7:1154](https://github.com/accuknox/discovery-engine/actions/runs/4118258190/jobs/7155494607#step:7:1154) here after 300 secs we are getting a policy with different port and with no protocol.

**Expected Behaviour :**
Discovery engine should generate a valid network policy after some iterations which means the policies should have proper defined ports as well as protocol

**Comment by Prateeknandle** [comment]
@seswarrajan do you have any comments to add?

**Comment by seswarrajan** [comment]
I will check and update. In the meantime, while running DE, please check side-by-side if Kubearmor logs shows that network data as well.

**Comment by Prateeknandle** [comment]
@seswarrajan any update on this? Did you find out this is a problem occuring, so we can stop testing discovery engine for a time being

**Comment by seswarrajan** [comment]
As i mentioned earlier, please run **karmor logs --logFilter all --operation Network** .
We can see if logs are missing or not.

**Comment by Prateeknandle** [comment]
@seswarrajan do we need the logs after the deployment of `wordpress-mysql` app ? Or do we need to apply a network policy and generate some alerts?

**Comment by Prateeknandle** [comment]
Found out that they are getting discovered but sometimes it takes too much time, closing the issue
