### ISSUE TITLE
[bug] multiple entries for same process in karmor summary (vault app)

### ISSUE THREAD

**Issue by yasin-cs-ko-ak** [accuknox/discovery-engine#668]
Screenshot:
![image](https://user-images.githubusercontent.com/92008211/218064601-0204826c-9939-4388-9a01-048ede2462f3.png)

To Reproduce this issue:
```console
$ helm repo add hashicorp https://helm.releases.hashicorp.com
"hashicorp" has been added to your repositories

$ helm install vault hashicorp/vault
```
and run `karmor summary`

**Comment by seswarrajan** [comment]
I will look into this issue

**Comment by Prateeknandle** [comment]
I'm also getting same issue with `wordpress-mysql` deployment

**Comment by yasin-cs-ko-ak** [comment]
@Prateeknandle Can you share the screenshot for that? Thanks

**Comment by Prateeknandle** [comment]
![Screenshot from 2023-03-13 17-30-03](https://user-images.githubusercontent.com/56027872/224696080-501d1eb1-4d8c-4770-bdf4-29e1d8ace7fe.png)

**Comment by yasin-cs-ko-ak** [comment]
@Prateeknandle The destination is different is right?
I don't think it's an issue. It's happening with vault only.

**Comment by Prateeknandle** [comment]
> @Prateeknandle The destination is different is right?

destination is repeating for same `src process` ig that is the problem. ex - for `/bin/bash` we get `/usr/bin/head` twice
