### ISSUE TITLE
Remove dependency on `github.com/kubearmor/KubeArmor/tests`

### ISSUE THREAD

**Issue by Vyom-Yadav** [accuknox/discovery-engine#718]
https://github.com/accuknox/discovery-engine/blob/5d03ee9f33586594154490671616dd2f1cb97925/tests/go.mod#L1-L6

`github.com/kubearmor/discovery-engine/tests` depends on `github.com/kubearmor/KubeArmor/tests`. `github.com/kubearmor/KubeArmor/tests` uses old dependency versions prohibiting updating dependencies in this module.

The only package it uses is `github.com/kubearmor/KubeArmor/tests/util`. 

Tasks in this issue:
- Remove dependency on `github.com/kubearmor/KubeArmor/tests`
- Migrate existing dependency usages in [`smoke_test.go`](https://github.com/accuknox/discovery-engine/blob/dev/tests/smoke/smoke_test.go) and [`recommned_test.go`](https://github.com/accuknox/discovery-engine/blob/dev/tests/recommend/recommned_test.go)

**Comment by Vyom-Yadav** [comment]
@nyrahul Can you assign this issue to someone?

**Comment by nyrahul** [comment]
Hey @stefin9898 , can you please take up this issue at the earliest? Thanks

**Comment by Vyom-Yadav** [comment]
Completed in https://github.com/accuknox/discovery-engine/pull/719
