### ISSUE TITLE
karmor summary bug: Failed to unmarshal the received message

### ISSUE THREAD

**Issue by zhy76** [accuknox/discovery-engine#762]
![image](https://github.com/accuknox/discovery-engine/assets/56665618/ef1fa656-21e8-4cb1-84f9-e3338d717c67)
![image](https://github.com/accuknox/discovery-engine/assets/56665618/b29ac2b5-9fa7-48c4-a98a-2435325b2f1f)
![image](https://github.com/accuknox/discovery-engine/assets/56665618/cfd24861-693a-402f-9fe7-06df6751e7e4)
![image](https://github.com/accuknox/discovery-engine/assets/56665618/1cb9bfe4-e07a-4917-814a-abbf7fb8d52c)
I use karmor summary -p mysql-5df4cd65d5-m5dlg can get data
![image](https://github.com/accuknox/discovery-engine/assets/56665618/c3629922-6ba1-4c7e-ad83-4298fb4e0022)
But use karmor summary -p wordpress-c4bf5b44b-fcvfc -o json get this error:
![image](https://github.com/accuknox/discovery-engine/assets/56665618/5c8bdcbf-81d9-4890-8449-edfd0203bda9)

**Comment by Ankurk99** [comment]
Will be solved by: https://github.com/kubearmor/kubearmor-client/pull/343
