### ISSUE TITLE
Scraping spammy sales info from LinkedIn and GitHub to peddle your wares

### ISSUE THREAD

**Issue by andyshinn** [accuknox/discovery-engine#772]
Just want to remind anyone seeing this that AccuKnox sales team is using services and / or themselves scraping information from GitHub and LinkedIn to call / email about selling their services. Scummy tactics. You are now on my shitlist and I will be sure to be vocal about it anytime your name comes up in the future.

**Comment by nyrahul** [comment]
Hey @andyshinn, I have sent this remark internally to our sales team. I will ensure to raise this issue in the internal meetings. Apologies for any unwarranted distraction this had for you.
